# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/schemas/__init__.py, backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_sqlmodel_from_sql.py
# ---------------------------------------------

import enum
from datetime import datetime, timezone
from typing import Any, Optional, cast
from uuid import UUID, uuid4

from sqlalchemy.dialects.postgresql import JSON
from sqlmodel import Column, Enum, Field, SQLModel


def enum_values(enum_class: type[enum.Enum]) -> list[str]:
    """Get values for enum."""
    return [status.value for status in enum_class]


class ActorType(str, enum.Enum):
    USER = "user"
    JOB_MANAGER = "job_manager"
    JOB_PROCESSOR = "job_processor"
    WORKER_PROCESS = "worker_process"
    SYSTEM = "system"


class AssetUploadStatus(str, enum.Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    READY = "ready"
    INVALID_MIME = "invalid_mime"
    PROCESSING_FAILED = "processing_failed"
    UPLOAD_FAILED = "upload_failed"
    UPLOAD_SUCCEEDED = "upload_succeeded"


class CommentStatus(str, enum.Enum):
    VISIBLE = "visible"
    HIDDEN_BY_AUTHOR = "hidden_by_author"
    DELETED_BY_SYSTEM = "deleted_by_system"


class FontStyle(str, enum.Enum):
    UNSPECIFIED = "unspecified"


class JobEventAction(str, enum.Enum):
    JOB_QUEUED = "job_queued"
    JOB_DEQUEUED = "job_dequeued"
    ATTEMPT_STARTED = "attempt_started"
    JOB_SUCCEEDED = "job_succeeded"
    ATTEMPT_FAILED = "attempt_failed"
    ATTEMPT_RETRY_SCHEDULED = "attempt_retry_scheduled"
    ATTEMPT_RETRY_EXHAUSTED = "attempt_retry_exhausted"
    JOB_MARKED_DEAD = "job_marked_dead"
    MANUAL_ATTEMPT_STARTED = "manual_attempt_started"
    JOB_ENQUEUE_FAILED = "job_enqueue_failed"
    LOG_INFO = "log_info"
    LOG_WARNING = "log_warning"
    LOG_EXCEPTION = "log_exception"


class JobStatus(str, enum.Enum):
    QUEUED = "queued"
    DEQUEUED = "dequeued"
    PROCESSING = "processing"
    DONE = "done"
    ERROR = "error"
    DEAD = "dead"
    ENQUEUE_FAILED = "enqueue_failed"


class NotificationStatus(str, enum.Enum):
    PENDING = "pending"
    SENT = "sent"
    FAILED = "failed"


class PhotobookStatus(str, enum.Enum):
    DRAFT = "draft"
    PENDING = "pending"
    DELETED = "deleted"
    PERMANENTLY_DELETED = "permanently_deleted"
    PUBLISHED = "published"
    UPLOADING = "uploading"
    UPLOAD_FAILED = "upload_failed"
    READY_FOR_GENERATION = "ready_for_generation"
    GENERATING = "generating"
    GENERATION_FAILED = "generation_failed"


class PhotobookStatusEditor(str, enum.Enum):
    USER = "user"
    UPLOAD_PIPELINE = "upload_pipeline"
    GENERATION_PIPELINE = "generation_pipeline"
    SYSTEM = "system"


class UserProvidedOccasion(str, enum.Enum):
    WEDDING = "wedding"
    BIRTHDAY = "birthday"
    ANNIVERSARY = "anniversary"
    OTHER = "other"


class DAOAssets(SQLModel, table=True):
    __tablename__ = cast("Any", "assets")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    user_id: UUID = Field(nullable=False)
    asset_key_original: Optional[str] = Field(default=None, nullable=True)
    asset_key_display: Optional[str] = Field(default=None, nullable=True)
    asset_key_llm: Optional[str] = Field(default=None, nullable=True)
    metadata_json: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    original_photobook_id: Optional[UUID] = Field(default=None, nullable=True)
    upload_status: AssetUploadStatus = Field(
        sa_column=Column(
            Enum(
                AssetUploadStatus,
                name="asset_upload_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    original_filename: Optional[str] = Field(default=None, nullable=True)
    exif: Optional[dict[str, Any]] = Field(default=None, nullable=True, sa_type=JSON)
    blur_data_url: Optional[str] = Field(default=None, nullable=True)


class DAOJobEvents(SQLModel, table=True):
    __tablename__ = cast("Any", "job_events")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    job_id: UUID = Field(nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    event_action: JobEventAction = Field(
        sa_column=Column(
            Enum(
                JobEventAction,
                name="job_event_action",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    message: Optional[str] = Field(default=None, nullable=True)
    host: Optional[str] = Field(default=None, nullable=True)
    retry_count: Optional[int] = Field(default=0, nullable=True)
    extra: Optional[dict[str, Any]] = Field(default=None, nullable=True, sa_type=JSON)
    actor_type: ActorType = Field(
        sa_column=Column(
            Enum(
                ActorType,
                name="actor_type",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    actor_id: Optional[str] = Field(default=None, nullable=True)
    job_type: Optional[str] = Field(default=None, nullable=True)
    photobook_id: Optional[UUID] = Field(default=None, nullable=True)


class DAOJobs(SQLModel, table=True):
    __tablename__ = cast("Any", "jobs")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    job_type: str = Field(nullable=False)
    status: JobStatus = Field(
        sa_column=Column(
            Enum(
                JobStatus,
                name="job_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    input_payload: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )
    result_payload: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )
    error_message: Optional[str] = Field(default=None, nullable=True)
    user_id: Optional[UUID] = Field(default=None, nullable=True)
    photobook_id: Optional[UUID] = Field(default=None, nullable=True)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    started_at: Optional[datetime] = Field(default=None, nullable=True)
    completed_at: Optional[datetime] = Field(default=None, nullable=True)
    retry_count: Optional[int] = Field(default=0, nullable=True)
    max_retries: Optional[int] = Field(default=3, nullable=True)
    last_attempted_at: Optional[datetime] = Field(default=None, nullable=True)


class DAOPages(SQLModel, table=True):
    __tablename__ = cast("Any", "pages")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: Optional[UUID] = Field(default=None, nullable=True)
    page_number: int = Field(nullable=False)
    user_message: Optional[str] = Field(default=None, nullable=True)
    layout: Optional[str] = Field(default=None, nullable=True)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    user_message_alternative_options: Optional[dict[str, Any]] = Field(
        default=None, nullable=True, sa_type=JSON
    )


class DAOPagesAssetsRel(SQLModel, table=True):
    __tablename__ = cast("Any", "pages_assets_rel")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    page_id: Optional[UUID] = Field(default=None, nullable=True)
    asset_id: Optional[UUID] = Field(default=None, nullable=True)
    order_index: Optional[int] = Field(default=None, nullable=True)
    caption: Optional[str] = Field(default=None, nullable=True)


class DAOPhotobookBookmarks(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_bookmarks")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    user_id: UUID = Field(nullable=False)
    photobook_id: UUID = Field(nullable=False)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    source: Optional[str] = Field(default=None, nullable=True)


class DAOPhotobookComments(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_comments")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    user_id: Optional[UUID] = Field(default=None, nullable=True)
    guest_name: Optional[str] = Field(default=None, nullable=True)
    guest_email: Optional[str] = Field(default=None, nullable=True)
    body: str = Field(nullable=False)
    status: CommentStatus = Field(
        sa_column=Column(
            Enum(
                CommentStatus,
                name="comment_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    notification_status: NotificationStatus = Field(
        sa_column=Column(
            Enum(
                NotificationStatus,
                name="notification_status",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    commenter_ip: Optional[str] = Field(default=None, nullable=True)
    user_agent: Optional[str] = Field(default=None, nullable=True)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    updated_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    last_updated_by: Optional[UUID] = Field(default=None, nullable=True)


class DAOPhotobookSettings(SQLModel, table=True):
    __tablename__ = cast("Any", "photobook_settings")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    photobook_id: UUID = Field(nullable=False)
    main_style: Optional[str] = Field(default=None, nullable=True)
    font: FontStyle = Field(
        sa_column=Column(
            Enum(
                FontStyle,
                name="font_style",
                native_enum=True,
                nullable=False,
                values_callable=enum_values,
            )
        )
    )
    is_comment_enabled: bool = Field(default=False, nullable=False)
    is_allow_download_all_images_enabled: bool = Field(default=False, nullable=False)
    is_tipping_enabled: bool = Field(default=False, nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )


class DAOPhotobooks(SQLModel, table=True):
    __tablename__ = cast("Any", "photobooks")
    id: UUID = Field(primary_key=True, default_factory=uuid4, nullable=False)
    user_id: UUID = Field(nullable=False)
    title: str = Field(nullable=False)
    caption: Optional[str] = Field(default=None, nullable=True)
    theme: Optional[str] = Field(default=None, nullable=True)
    status: Optional[PhotobookStatus] = Field(
        sa_column=Column(
            Enum(
                PhotobookStatus,
                name="photobook_status",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        )
    )
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    updated_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=True
    )
    user_provided_occasion: Optional[UserProvidedOccasion] = Field(
        default=None,
        sa_column=Column(
            Enum(
                UserProvidedOccasion,
                name="user_provided_occasion",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        ),
    )
    user_provided_occasion_custom_details: Optional[str] = Field(
        default=None, nullable=True
    )
    user_provided_context: Optional[str] = Field(default=None, nullable=True)
    thumbnail_asset_id: Optional[UUID] = Field(default=None, nullable=True)
    deleted_at: Optional[datetime] = Field(default=None, nullable=True)
    status_last_edited_by: Optional[PhotobookStatusEditor] = Field(
        sa_column=Column(
            Enum(
                PhotobookStatusEditor,
                name="photobook_status_editor",
                native_enum=True,
                nullable=True,
                values_callable=enum_values,
            )
        )
    )


class DAOUserRecentlyViewedPhotobook(SQLModel, table=True):
    __tablename__ = cast("Any", "user_recently_viewed_photobook")
    user_id: UUID = Field(primary_key=True, nullable=False)
    photobook_id: UUID = Field(primary_key=True, nullable=False)
    viewed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )


class DAOUsers(SQLModel, table=True):
    __tablename__ = cast("Any", "users")
    id: UUID = Field(primary_key=True, nullable=False)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), nullable=False
    )
    email: Optional[str] = Field(default=None, nullable=True)
    phone: Optional[str] = Field(default=None, nullable=True)
    email_confirmed_at: Optional[datetime] = Field(default=None, nullable=True)
    phone_confirmed_at: Optional[datetime] = Field(default=None, nullable=True)
    name: Optional[str] = Field(default=None, nullable=True)
    role: str = Field(default="user'::text", nullable=False)
