# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_crud_schemas.py
# ---------------------------------------------

from datetime import datetime
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict
from sqlmodel import Field

from db.data_models import (
    ActorType,
    AssetUploadStatus,
    CommentStatus,
    FontStyle,
    JobEventAction,
    JobStatus,
    NotificationStatus,
    PhotobookStatus,
    PhotobookStatusEditor,
    UserProvidedOccasion,
)


class WritableModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)  # used for Create/Update


class DAOAssetsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    user_id: UUID
    asset_key_original: Optional[str] = None
    asset_key_display: Optional[str] = None
    asset_key_llm: Optional[str] = None
    metadata_json: Optional[dict[str, Any]] = None
    original_photobook_id: Optional[UUID] = None
    upload_status: AssetUploadStatus
    original_filename: Optional[str] = None
    exif: Optional[dict[str, Any]] = None
    blur_data_url: Optional[str] = None


class DAOAssetsUpdate(WritableModel):
    user_id: Optional[UUID] = None
    asset_key_original: Optional[str] = None
    asset_key_display: Optional[str] = None
    asset_key_llm: Optional[str] = None
    metadata_json: Optional[dict[str, Any]] = None
    original_photobook_id: Optional[UUID] = None
    upload_status: Optional[AssetUploadStatus] = None
    original_filename: Optional[str] = None
    exif: Optional[dict[str, Any]] = None
    blur_data_url: Optional[str] = None


class DAOJobEventsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    job_id: UUID
    event_action: JobEventAction
    message: Optional[str] = None
    host: Optional[str] = None
    retry_count: Optional[int] = None
    extra: Optional[dict[str, Any]] = None
    actor_type: ActorType
    actor_id: Optional[str] = None
    job_type: Optional[str] = None
    photobook_id: Optional[UUID] = None


class DAOJobEventsUpdate(WritableModel):
    job_id: Optional[UUID] = None
    event_action: Optional[JobEventAction] = None
    message: Optional[str] = None
    host: Optional[str] = None
    retry_count: Optional[int] = None
    extra: Optional[dict[str, Any]] = None
    actor_type: Optional[ActorType] = None
    actor_id: Optional[str] = None
    job_type: Optional[str] = None
    photobook_id: Optional[UUID] = None


class DAOJobsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    job_type: str
    status: JobStatus
    input_payload: Optional[dict[str, Any]] = None
    result_payload: Optional[dict[str, Any]] = None
    error_message: Optional[str] = None
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retry_count: Optional[int] = None
    max_retries: Optional[int] = None
    last_attempted_at: Optional[datetime] = None


class DAOJobsUpdate(WritableModel):
    job_type: Optional[str] = None
    status: Optional[JobStatus] = None
    input_payload: Optional[dict[str, Any]] = None
    result_payload: Optional[dict[str, Any]] = None
    error_message: Optional[str] = None
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retry_count: Optional[int] = None
    max_retries: Optional[int] = None
    last_attempted_at: Optional[datetime] = None


class DAOPagesCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: Optional[UUID] = None
    page_number: int
    user_message: Optional[str] = None
    layout: Optional[str] = None
    user_message_alternative_options: Optional[dict[str, Any]] = None


class DAOPagesUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    page_number: Optional[int] = None
    user_message: Optional[str] = None
    layout: Optional[str] = None
    user_message_alternative_options: Optional[dict[str, Any]] = None


class DAOPagesAssetsRelCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    page_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None
    order_index: Optional[int] = None
    caption: Optional[str] = None


class DAOPagesAssetsRelUpdate(WritableModel):
    page_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None
    order_index: Optional[int] = None
    caption: Optional[str] = None


class DAOPhotobookBookmarksCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    user_id: UUID
    photobook_id: UUID
    source: Optional[str] = None


class DAOPhotobookBookmarksUpdate(WritableModel):
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    source: Optional[str] = None


class DAOPhotobookCommentsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    user_id: Optional[UUID] = None
    guest_name: Optional[str] = None
    guest_email: Optional[str] = None
    body: str
    status: CommentStatus
    notification_status: NotificationStatus
    commenter_ip: Optional[str] = None
    user_agent: Optional[str] = None
    last_updated_by: Optional[UUID] = None


class DAOPhotobookCommentsUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    guest_name: Optional[str] = None
    guest_email: Optional[str] = None
    body: Optional[str] = None
    status: Optional[CommentStatus] = None
    notification_status: Optional[NotificationStatus] = None
    commenter_ip: Optional[str] = None
    user_agent: Optional[str] = None
    updated_at: Optional[datetime] = None
    last_updated_by: Optional[UUID] = None


class DAOPhotobookSettingsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    main_style: Optional[str] = None
    font: FontStyle
    is_comment_enabled: bool
    is_allow_download_all_images_enabled: bool
    is_tipping_enabled: bool


class DAOPhotobookSettingsUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    main_style: Optional[str] = None
    font: Optional[FontStyle] = None
    is_comment_enabled: Optional[bool] = None
    is_allow_download_all_images_enabled: Optional[bool] = None
    is_tipping_enabled: Optional[bool] = None
    updated_at: Optional[datetime] = None


class DAOPhotobooksCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    user_id: UUID
    title: str
    caption: Optional[str] = None
    theme: Optional[str] = None
    status: Optional[PhotobookStatus] = None
    user_provided_occasion: Optional[UserProvidedOccasion] = None
    user_provided_occasion_custom_details: Optional[str] = None
    user_provided_context: Optional[str] = None
    thumbnail_asset_id: Optional[UUID] = None
    deleted_at: Optional[datetime] = None
    status_last_edited_by: Optional[PhotobookStatusEditor] = None


class DAOPhotobooksUpdate(WritableModel):
    user_id: Optional[UUID] = None
    title: Optional[str] = None
    caption: Optional[str] = None
    theme: Optional[str] = None
    status: Optional[PhotobookStatus] = None
    updated_at: Optional[datetime] = None
    user_provided_occasion: Optional[UserProvidedOccasion] = None
    user_provided_occasion_custom_details: Optional[str] = None
    user_provided_context: Optional[str] = None
    thumbnail_asset_id: Optional[UUID] = None
    deleted_at: Optional[datetime] = None
    status_last_edited_by: Optional[PhotobookStatusEditor] = None


class DAOUserRecentlyViewedPhotobookCreate(WritableModel):
    user_id: UUID
    photobook_id: UUID
    viewed_at: datetime


class DAOUserRecentlyViewedPhotobookUpdate(WritableModel):
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    viewed_at: Optional[datetime] = None


class DAOUsersCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    email: Optional[str] = None
    phone: Optional[str] = None
    email_confirmed_at: Optional[datetime] = None
    phone_confirmed_at: Optional[datetime] = None
    name: Optional[str] = None
    role: str


class DAOUsersUpdate(WritableModel):
    email: Optional[str] = None
    phone: Optional[str] = None
    email_confirmed_at: Optional[datetime] = None
    phone_confirmed_at: Optional[datetime] = None
    name: Optional[str] = None
    role: Optional[str] = None
